### ISSUE TITLE
Pull to refresh not visible on swift 3.0

### ISSUE THREAD

**Issue by learnwithgabbar** [DanisFabric/Infinity#11]

**Comment by paresh-navadiya** [comment]
I am facing same issue. @DanisFabric Is there any solution for this

**Comment by DanisFabric** [comment]
@paresh-navadiya You update Infinity to 3.0, I solved this problem.

**Comment by paresh-navadiya** [comment]
@DanisFabric : Can you update the pod so I can update pod in my project

**Comment by DanisFabric** [comment]
@paresh-navadiya dont support cocoapods any more, I think carthage is much better than pod

**Comment by DanisFabric** [comment]
@paresh-navadiya I pushed Infinity3.0.1 to cocoapods
