### ISSUE TITLE
Can I temporarily disable pull-to-refresh?

### ISSUE THREAD

**Issue by vietstone-ng** [DanisFabric/Infinity#12]
Hi,
I want to use pull-to-refresh. But sometimes, I want to disable it, then enable later.
Can I do it with this library?
Thank you.

**Comment by paresh-navadiya** [comment]
When want to diable use **removePullToRefresh** and when want to enable use **addPullToRefresh**

**Comment by DanisFabric** [comment]
@paresh-navadiya 

```
tableView.fty.pullToRefresh.isEnabled = false    // disable the pull-to-refresh in Infinity3.0
tableView.isPullToRefreshEnabled = false          // disable the pull-to-refresh before Infinity3.0
```

**Comment by vietstone-ng** [comment]
Oh, thank you @DanisFabric . Btw, I think you should update Readme's Introduction. It says the library is written in Swift 2.1. But I think it's on Swift 3.0 already.
Thank you @paresh-navadiya , anw.

**Comment by DanisFabric** [comment]
I have already updated readme file 😀

**Comment by vietstone-ng** [comment]
oup, how about this

> Infinity is a simple to use library written in _Swift2.1_

**Comment by DanisFabric** [comment]
@vietstone fix it. thx a lot 😂
