### ISSUE TITLE
The tableView scrolls to bottom automatically when I call tableView.fty.infiniteScroll.begin()

### ISSUE THREAD

**Issue by vietstone-ng** [DanisFabric/Infinity#13]
Hi, when I call tableView.fty.infiniteScroll.begin(), then tableView scrolls to bottom automatically. If I want the tableView not scrolling, how can I do? Thank you.

**Comment by DanisFabric** [comment]
loadMore() depends on the `contentOffset` of tableView, So Infinity must scroll to bottom

**Comment by vietstone-ng** [comment]
oh, ok. I get it. Thank you.
