### ISSUE TITLE
Swift 3 Xcode Beta 4 

### ISSUE THREAD

**Issue by ed-mejia** [DanisFabric/Infinity#7]
Hi There!!, I needed the lib to [support Swift 3 Xcode Beta 4](https://github.com/ed-mejia/Infinity/tree/swift3) so I migrate it..

If you create a swift3 branch I could pull request to sync it if you want.

**Comment by Douvi** [comment]
I will need too, @DanisFabric could you open a new branch swift3 ? 
@ed-mejia Apple just release the official version of Xcode 8 on App Store ([link](https://itunes.apple.com/fr/app/xcode/id497799835?l=en&mt=12))

**Comment by DanisFabric** [comment]
I have opened a new branch swift3.0
